# This playbook install the latest version of Wordpress and his requirements
#
# Copyright (c) 2016 Roman Martin
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- hosts: all
  tasks:
    - name: Update packages (this is equivalent to yum update -y)
      yum: name=* state=latest
    - name: Install Apache and extras
      yum: name={{ item }} state=present
      with_items:
      - httpd
      - php 
      - php-mysql
      - MySQL-python
    - name: Ensure Apache is running (and enable it at boot)
      service: name=httpd state=started enabled=yes
